# Spring Boot应用配置
spring:
  # 数据库配置
  datasource:
    # 默认使用H2内存数据库，方便开发和测试
    #url: jdbc:h2:mem:edusystem
    #driver-class-name: org.h2.Driver
    #username: sa
    #password: 
    
    # MySQL配置
    url: jdbc:mysql://127.0.0.1:3306/edusystem?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
  
  # JPA配置
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        #dialect: org.hibernate.dialect.H2Dialect
        # MySQL方言，使用MySQL时取消注释
        dialect: org.hibernate.dialect.MySQL8Dialect
  
  # H2控制台配置
  h2:
    console:
      enabled: true
      path: /h2-console

# 应用服务器配置
server:
  port: 3000
  servlet:
    context-path: /api

# JWT配置
jwt:
  secret: edusystemSecretKey123456789012345678901234567890
  expiration: 86400000 # 24小时，单位毫秒

# 日志配置
logging:
  level:
    root: INFO
    com.edusys: DEBUG
    org.springframework.web: INFO
    org.hibernate: INFO